plugins:
    radon:
        is_active: true
        endpoints:
            query:
                backends:
                    NIEP:
                        country_code: "RO"
                        country: "Romania"
                        name: "National Institute for Earth Physics"
                        geometry: [[19.50, 49.00], [30.00, 49.00], [30.00, 42.0], [19.50, 42.0], [19.50, 49.00]]
                        url: "https://radon.infp.ro/query"
                    INGV:
                        country_code: "IT"
                        country: "Italy"
                        name: "ISTITUTO NAZIONALE DI GEOFIZICA E VULCANOLOGIA"
                        geometry: [[11.78, 43.95], [13.61, 43.95], [13.61, 42.8], [11.78, 42.8], [11.78, 43.95]]
                        url: "http://webservices.ingv.it/ingvws/nfo_taboo/radon/1/query"
